name: flow

dependencies:
    - python==3.5.2
    - path.py
    - setuptools==39.1.0
    - pip:
        - dill
        - lz4
        - setproctitle
        - psutil
        - boto3==1.4.8
        - redis~=2.10.6
        - git+https://github.com/Theano/Theano.git@adfe319ce6b781083d8dc3200fb4481b00853791#egg=Theano
        - git+https://github.com/neocxi/Lasagne.git@484866cf8b38d878e92d521be445968531646bb8#egg=Lasagne
        - git+https://github.com/plotly/plotly.py.git@2594076e29584ede2d09f2aa40a8a195b3f3fc66#egg=plotly
